# Generated by Django 3.1.4 on 2021-01-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nicotineacid', models.FloatField(blank=True)),
                ('riboflavin', models.FloatField(blank=True)),
                ('benfotiamin', models.FloatField(blank=True)),
                ('biotin', models.FloatField(blank=True)),
                ('zinc', models.FloatField(blank=True)),
                ('cyanocobalamin', models.FloatField(blank=True)),
                ('udca', models.FloatField(blank=True)),
                ('inositol', models.FloatField(blank=True)),
                ('choline', models.FloatField(blank=True)),
                ('tocopherol', models.FloatField(blank=True)),
                ('pantothenicacid', models.FloatField(blank=True)),
                ('folicacid', models.FloatField(blank=True)),
                ('pyridoxine', models.FloatField(blank=True)),
                ('selenium', models.FloatField(blank=True)),
                ('ascrobicacid', models.FloatField(blank=True)),
            ],
        ),
    ]
