# Generated by Django 3.1.4 on 2021-03-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multivitamin', '0005_auto_20210323_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='benfotiamin',
        ),
    ]
